### PR TITLE
Update ModelView.js

### PR DESCRIPTION
**Pull request by lucaslokchan**
Render Error
Text strings must be rendered with a component

### CODE REVIEW

**Comment by jude253** [comment]
Hey! @lucaslokchan thanks for adding this! Does it work on your local device?

**Comment by lucaslokchan** [comment]
Hi @jude253, It doesn't work on my device, let me have a close look

**Comment by jude253** [comment]
ok @lucaslokchan ! sounds good! Try the old version too and see if that works and let me know if you are able to get it working! :)

**Comment by lucaslokchan** [comment]
@jude253 It works on my device now, I can see output arrays of poses in terminal.

I am going to plot the skeleton on screen, thanks for you awesome work!

output


image

**Comment by jude253** [comment]
@lucaslokchan you are welcome! I will double check this works on my phone and merge it if it does!

**Review by jude253 — APPROVED** [review]
Thanks for making this! It works perfectly, sorry it took me so long to review!

**Pull request merged**
